default_platform(:ios)

platform :ios do
  desc "Build and upload a beta build to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"]
    )

    match(
      type: "appstore",
      app_identifier: "com.gamejam.morichan",
      readonly: ENV["CI"] == "true",
      api_key: api_key
    )

    latest_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "com.gamejam.morichan"
    )

    increment_build_number(
      build_number: latest_build + 1,
      xcodeproj: "Closer.xcodeproj"
    )

    build_app(
      project: "Closer.xcodeproj",
      scheme: "Closer"
    )

    upload_to_testflight(
      api_key: api_key,
      distribute_external: true,
      groups: ["External Testers"],
      notify_external_testers: true,
      changelog: "Latest build for testing."
    )
  end
end
