name: TestFlight

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - feature/cicd

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.6'
          bundler-cache: true

      - name: Setup SSH for match
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MATCH_GIT_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Test certificates repo access
        run: git ls-remote git@github.com:syahraazly/ios-certificates.git

      - name: Run fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
        run: bundle exec fastlane beta
